defaults:
  - _self_
  - wandb: private.yaml
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

# disable hydra outputs
hydra:
  output_subdir: null
  run:
    dir: .

name: "byol-clustervec-linear"
pretrained_feature_extractor: /home/larbez/Documents/solo-learn/trained_models/byol/2ak6hi81/test-byol-dataset-clustervec-2ak6hi81-ep=3999.ckpt
backbone:
  name: "resnet18"
pretrain_method: "byol"
data:
  dataset: custom
  train_path: "/scratch2/clear/larbez/Workspace/datasets/CLIP/split_10-30/train_b"
  val_path: "/scratch2/clear/larbez/Workspace/datasets/CLIP/split_10-30/test"
  format: "ImageFolder"
  num_workers: 8
  num_classes: 151
optimizer:
  name: "sgd"
  batch_size: 256
  lr: 0.1
  weight_decay: 0
scheduler:
  name: "step"
  lr_decay_steps: [60, 80]
checkpoint:
  enabled: True
  dir: "trained_models"
  frequency: 1
auto_resume:
  enabled: True

# overwrite PL stuff
max_epochs: 100
devices: [0]
sync_batchnorm: True
accelerator: "gpu"
strategy: "ddp"
precision: 16
